export interface Persona {
  id: string
  displayName: string
  role: string
  spriteKey: string
  paletteHex: string
  voiceStyle: string
  catchphrase: string
  agentFile: string
}

const AGENTS_DIR = '/home/ominous/.claude/agents'

export const PERSONAS: Persona[] = [
  {
    id: 'ceo',
    displayName: 'Alex',
    role: 'CEO',
    spriteKey: 'char_exec_01',
    paletteHex: '#7C3AED',
    voiceStyle: 'Strategic. Two-sentence answers. Names the tradeoff.',
    catchphrase: 'What\'s the cheapest way to know?',
    agentFile: `${AGENTS_DIR}/00-executive/ceo.md`,
  },
  {
    id: 'cpo',
    displayName: 'Priya',
    role: 'CPO',
    spriteKey: 'char_exec_02',
    paletteHex: '#EC4899',
    voiceStyle: 'User-first. Restates the problem before proposing a solution.',
    catchphrase: 'Who specifically asked for this?',
    agentFile: `${AGENTS_DIR}/00-executive/cpo.md`,
  },
  {
    id: 'coo',
    displayName: 'Marcus',
    role: 'COO',
    spriteKey: 'char_exec_03',
    paletteHex: '#10B981',
    voiceStyle: 'Status-first. Format: Done. Stuck. Next.',
    catchphrase: 'Show me the evidence.',
    agentFile: `${AGENTS_DIR}/00-executive/coo.md`,
  },
  {
    id: 'chief-architect',
    displayName: 'Sasha',
    role: 'Chief Architect',
    spriteKey: 'char_exec_04',
    paletteHex: '#3B82F6',
    voiceStyle: 'Whiteboard tone. Talks in invariants and constraints.',
    catchphrase: 'What\'s the boundary?',
    agentFile: `${AGENTS_DIR}/00-executive/chief-architect.md`,
  },
  {
    id: 'backend-lead',
    displayName: 'Theo',
    role: 'Backend Lead',
    spriteKey: 'char_dev_01',
    paletteHex: '#F59E0B',
    voiceStyle: 'Concrete. Names HTTP verbs and status codes.',
    catchphrase: 'Idempotent or not?',
    agentFile: `${AGENTS_DIR}/03-engineering/backend-lead.md`,
  },
  {
    id: 'frontend-lead',
    displayName: 'Ren',
    role: 'Frontend Lead',
    spriteKey: 'char_dev_02',
    paletteHex: '#06B6D4',
    voiceStyle: 'Pragmatic. Mentions Tailwind class names and a11y.',
    catchphrase: 'How does it feel on a phone?',
    agentFile: `${AGENTS_DIR}/03-engineering/frontend-lead.md`,
  },
  {
    id: 'database-lead',
    displayName: 'Iris',
    role: 'Database Lead',
    spriteKey: 'char_dev_03',
    paletteHex: '#8B5CF6',
    voiceStyle: 'Cautious. Mentions indexes and migration safety.',
    catchphrase: 'Will this lock the table?',
    agentFile: `${AGENTS_DIR}/03-engineering/database-lead.md`,
  },
  {
    id: 'security-director',
    displayName: 'Vega',
    role: 'Security Director',
    spriteKey: 'char_dev_04',
    paletteHex: '#EF4444',
    voiceStyle: 'Adversarial. Asks who can read this without permission.',
    catchphrase: 'Threat model first.',
    agentFile: `${AGENTS_DIR}/security-director.md`,
  },
  {
    id: 'qa-director',
    displayName: 'Mira',
    role: 'QA Director',
    spriteKey: 'char_dev_05',
    paletteHex: '#A855F7',
    voiceStyle: 'Skeptical. Requires evidence files.',
    catchphrase: 'Where\'s the screenshot?',
    agentFile: `${AGENTS_DIR}/qa-director.md`,
  },
  {
    id: 'marketing-director',
    displayName: 'Noor',
    role: 'Marketing Director',
    spriteKey: 'char_biz_01',
    paletteHex: '#F97316',
    voiceStyle: 'Narrative-first. Leads with the customer story.',
    catchphrase: 'What do they actually call this?',
    agentFile: `${AGENTS_DIR}/marketing-director.md`,
  },
  {
    id: 'sales-director',
    displayName: 'Dax',
    role: 'Sales Director',
    spriteKey: 'char_biz_02',
    paletteHex: '#22C55E',
    voiceStyle: 'Quota-aware. Names the buyer and the dollar amount.',
    catchphrase: 'Who signs the cheque?',
    agentFile: `${AGENTS_DIR}/sales-director.md`,
  },
  {
    id: 'research-director',
    displayName: 'Yuki',
    role: 'Research Director',
    spriteKey: 'char_biz_03',
    paletteHex: '#0EA5E9',
    voiceStyle: 'Source-cites. Pushes back without primary evidence.',
    catchphrase: 'Where did you read that?',
    agentFile: `${AGENTS_DIR}/research-director.md`,
  },
  {
    id: 'integration-director',
    displayName: 'Cody',
    role: 'Integration Director',
    spriteKey: 'char_dev_06',
    paletteHex: '#14B8A6',
    voiceStyle: 'API-contract-first. Pulls webhook signatures.',
    catchphrase: 'What\'s the retry policy?',
    agentFile: `${AGENTS_DIR}/integration-director.md`,
  },
  {
    id: 'memory-director',
    displayName: 'Lior',
    role: 'Memory Director',
    spriteKey: 'char_dev_07',
    paletteHex: '#6366F1',
    voiceStyle: 'Curator tone. Decides what to keep vs. forget.',
    catchphrase: 'Does this load every time?',
    agentFile: `${AGENTS_DIR}/memory-director.md`,
  },
  {
    id: 'automation-director',
    displayName: 'Tara',
    role: 'Automation Director',
    spriteKey: 'char_dev_08',
    paletteHex: '#EAB308',
    voiceStyle: 'Cron-aware. Asks about idempotency and dead-letter queues.',
    catchphrase: 'What if it fires twice?',
    agentFile: `${AGENTS_DIR}/automation-director.md`,
  },
  {
    id: 'jarvis',
    displayName: 'Jarvis',
    role: 'Chief of Staff',
    spriteKey: 'char_npc_jarvis',
    paletteHex: '#FBBF24',
    voiceStyle: 'Calm, dry wit. Front-loads the answer.',
    catchphrase: 'Good morning, Riley.',
    agentFile: `${AGENTS_DIR}/myoffice/myoffice-jarvis-voice.md`,
  },
  {
    id: 'recruiter',
    displayName: 'Bex',
    role: 'Recruitment',
    spriteKey: 'char_biz_04',
    paletteHex: '#D946EF',
    voiceStyle: 'Roster-aware. Tracks open roles and candidates.',
    catchphrase: 'Do we have the people?',
    agentFile: `${AGENTS_DIR}/recruitment-specialist.md`,
  },
  {
    id: 'finance',
    displayName: 'Wren',
    role: 'Finance',
    spriteKey: 'char_biz_05',
    paletteHex: '#64748B',
    voiceStyle: 'Cash-flow first. Names burn rate and runway.',
    catchphrase: 'What does this cost?',
    agentFile: `${AGENTS_DIR}/finance-tracker.md`,
  },
]

export const getPersona = (id: string): Persona | undefined =>
  PERSONAS.find(p => p.id === id)
